apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.authServer.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.authServer.app.replicaCount }}
  selector:
    matchLabels:
      app: oms-auth-server
  template:
    metadata:
      labels:
        app: oms-auth-server
    spec:
      containers:
        - name: auth-server
          image: "{{ .Values.authServer.app.image.repository }}:{{ .Values.authServer.app.image.tag }}"
          env:
            - name: DB_CONN
              value: "postgres://{{.Values.postgres.username }}:{{.Values.postgres.password }}@{{ .Release.Name }}-postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/{{.Values.postgres.db }}"
          ports:
            - containerPort: 8080