apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.authServer.replicaCount }}
  selector:
    matchLabels:
      app: oms-auth-server
  template:
    metadata:
      labels:
        app: oms-auth-server
    spec:
      containers:
        - name: auth-server
          image: "{{ .Values.authServer.image.repository }}:{{ .Values.authServer.image.tag }}"
          env:
            - name: DB_CONN
              value: "postgres://{{.Values.postgres.username }}:{{.Values.postgres.password }}@{{.Values.postgres.url }}:5432/{{.Values.postgres.db }}"
          ports:
            - containerPort: 8080