apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.orderServer.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: oms-order-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: oms-order-server