apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
data:
  POSTGRES_DB: "{{.Values.postgres.db }}"
  POSTGRES_USER: "{{.Values.postgres.username }}"
  POSTGRES_PASSWORD: "{{.Values.postgres.password }}"