authServer:
  service:
    port: 8080
  app:
    name: auth-server
    replicaCount: 1
    image:
      repository: superm4n/auth-server
      tag: "latest"
orderServer:
  service:
    port: 9090
  app:
    name: order-server
    replicaCount: 1
    image:
      repository: superm4n/order-server
      tag: "latest"
orderProcessor:
  app:
    name: order-processor
    replicaCount: 1
    image:
      repository: superm4n/order-processor
      tag: "latest"
postgres:
  #  url: localhost
  #  url: oms-postgres.oms.svc.cluster.local #postgres service url
  username: postgres
  password: postgres
  db: oms
  replicas: 1
redis:
  serviceName: redis-master
  username: default
  password: redis
  db: oms
  replicas: 1